### ISSUE TITLE
One of the controllers takes over tracking of the other

### ISSUE THREAD

**Issue by GlubFun** [Timocop/PSMoveServiceEx-Virtual-Device-Manager#5] opened 2023-08-06 14:06 UTC
When i wanna play, and i set up VDM, most of the times, both controllers end up connected, i never understood why this happens but it does, usually restarting the software fixes it.

Here's a screenshots of the driver:

![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/94810861/20ec6dd8-9009-4a26-a636-1b4fada93baa)

![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/94810861/6a7d50dd-fe24-43a9-b1d1-bcc72bc52f5a)

![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/94810861/0629d341-5de9-429d-af02-63fd9b6378d5)

This is on steamvr Home so its more clear whats happening:

![image](https://github.com/Timocop/PSMoveServiceEx-Virtual-Device-Manager/assets/94810861/7f6070ed-8a1b-4170-9532-64618af66399)

Both are configured correcly, they are tracked separately but in the driver, they are tracked in the same position, buttons and trackpad are separated for each controller, its just the tracking and rotation whats wrong.

**Comment by Timocop** [comment] 2023-08-06 14:29
You dont need SteamVR overrides. Remove the overrides and it will work.
SteamVR overrides are **only** for 3rd party trackers to overrides their pose with PSMS-EX pose.

**Comment by Timocop** [comment] 2023-08-09 14:21
Closing this. Assuming the issue is fixed.

**Closed by Timocop** 2023-08-09 14:21 UTC
Labels: question
